### ISSUE TITLE
error in cargo run

### ISSUE THREAD

**Issue by taylorreiter** [taylorreiter/sourmap#5]
```
cargo run --release -- abundance-matrix --scaled 2000 --from-file -o abundance.csv <(find ../sandbox/bacteria/ -type f -iname "*sig")
```

fails with many lines of:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:85:43
```

ran as specified here:
https://github.com/taylorreiter/sourmap/blob/tr-readme/README.md

**Comment by taylorreiter** [comment]
Ah the error message actually had way more information, and I just missed it previously:

```
cargo run --release -- abundance-matrix --scaled 2000 --from-file -o abundance.csv <(find ~/github/s
ourmap/sandbox/ashkaan/sigs/ -type f -iname "*sig")
    Finished release [optimized] target(s) in 0.66s
     Running `target/release/sourmap abundance-matrix --scaled 2000 --from-file -o abundance.csv /dev/fd/63`
[2020-11-12T23:18:01Z INFO  sourmap] Loading siglist
[2020-11-12T23:18:01Z INFO  sourmap] Loaded 2617 sig paths in siglist
[2020-11-12T23:18:01Z INFO  sourmap] Processed 0 reference sigs
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:85:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:85:43
```

**Comment by taylorreiter** [comment]
andddd that's because these signatures are scaled 1000:

```
sig describe ../sandbox/ashkaan/sigs/GCA_001580115.1.sig

== This is sourmash version 3.5.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

---reading from file '../sandbox/ashkaan/sigs/GCA_001580115.1.sig'
signature filename: ../sandbox/ashkaan/sigs/GCA_001580115.1.sig
signature: GCA_001580115.1 Candidatus Stoquefichus sp. KLE1796 strain=KLE1796, ASM158011v1
source file: /dev/fd/63
md5: 63e3ec454c5d4658d5323b4dd45cc7f1
k=21 molecule=DNA num=0 scaled=1000 seed=42 track_abundance=1
size: 2940
signature license: CC0

---
signature filename: ../sandbox/ashkaan/sigs/GCA_001580115.1.sig
signature: GCA_001580115.1 Candidatus Stoquefichus sp. KLE1796 strain=KLE1796, ASM158011v1
source file: /dev/fd/63
md5: dbf7ffdd6a900cae03fc58998db7fabd
k=31 molecule=DNA num=0 scaled=1000 seed=42 track_abundance=1
size: 3171
signature license: CC0

---
signature filename: ../sandbox/ashkaan/sigs/GCA_001580115.1.sig
signature: GCA_001580115.1 Candidatus Stoquefichus sp. KLE1796 strain=KLE1796, ASM158011v1
source file: /dev/fd/63
md5: af92189ab33b6a2b7c3c64aaae9c9e97
k=51 molecule=DNA num=0 scaled=1000 seed=42 track_abundance=1
size: 3181
signature license: CC0

loaded 3 sigs from '../sandbox/ashkaan/sigs/GCA_001580115.1.sig'
loaded 3 signatures total.
(sourmap) tereiter@bm2:~/github/sourmap/sourmap_rs$ cargo run --release -- abundance-matrix --scaled 1000 --from-file -o abundance.csv <(find ~/github/sourmap/sandbox/ashkaan/sigs/ -type f -iname "*sig")
    Finished release [optimized] target(s) in 0.76s
     Running `target/release/sourmap abundance-matrix --scaled 1000 --from-file -o abundance.csv /dev/fd/63`
[2020-11-12T23:20:20Z INFO  sourmap] Loading siglist
[2020-11-12T23:20:20Z INFO  sourmap] Loaded 2617 sig paths in siglist
[2020-11-12T23:20:20Z INFO  sourmap] Processed 0 reference sigs
[2020-11-12T23:20:29Z INFO  sourmap] Processed 1000 reference sigs
[2020-11-12T23:20:41Z INFO  sourmap] Processed 2000 reference sigs
```

**Comment by luizirber** [comment]
Yeah, the error handling needs to be improved, especially in cases where the sig can be downsampled to the right scaled...
